= 메소드에 예외 선언
 
* 메소드에서 발생할 수 있는 예외를 메소드 선언부에 명시하여 알림
* 예외를 처리하는 것이 아니라 메소드 호출자에게 예외를 전달하여 떠넘김
* 예외가 선언된 메소드를 호출하는 쪽에서 예외를 처리해야 함

[source, java]
----
public int getMinute(int number) throws DateTimeException {
    …
}
----

---

메소드 내부에서 예외가 발생할 수 있는 코드를 작성할 때 try-catch문으로 예외를 처리하는 것이 일반적입니다. 하지만 경우에 따라서 메소드 내에서 예외를 직접 처리하지 않고 메소드를 호출한 곳으로 예외를 떠넘길 수도 있습니다. 

== 선언

메소드를 선언할 때 throws절을 사용하면 메소드 내에서 처리하지 않은 예외를 메소드를 호출한 곳에서 처리하도록 떠넘길 수 있습니다. 

[source, java]
----
public int getFileSize(String fileName) throws FileNotFoundException {
   …
}
----

메소드 선언부에 throws 절을 사용하여 처리를 떠넘길 예외 클래스를 명시하면 메소드를 호출하는 곳으로 처리를 떠넘길 수 있습니다. 아래와 같이 여러 예외를 명시할 수도 있습니다.

[source, java]
----
public int getFileSize(String fileName) throws FileNotFoundException, IOException {
   …
}
----
아래와 같이 throws 절에 Exception 클래스를 명시하면, Exception에서 파생된 모든 예외를 떠넘길 수 있습니다.

[source, java]
----
public int getFileSize(String fileName) throws Exception {
   …
}
----

== throws로 선언된 메소드 호출

`throws` 절과 함께 선언된 메소드는 반드시 `try` 블록내에서 호출되어야 하며, `catch` 절에서는 `throws` 절에서 명시한 예외를 처리하도록 작성되어야 합니다. 

[source, java]
----
public static int getFileSize(String fileName) throws IOException {
    return 1;
}

public static void main(String[] args) {
    try {
        TryCatch tryCatch = new TryCatch();
        tryCatch.getFileSize("a.java");
    }
    catch (IOException e) {
        e.printStackTrace();
    }
}
----

`catch` 절에서 호출하는 메소드에서 선언한 예외와 다른 타입의 예외를 호출하면 컴파일 오류가 발생합니다.

[source, java]
----
public int getFileSize(String fileName) throws IOException {
    return 1;
}

public static void main(String[] args) {
    try {
        TryCatch tryCatch = new TryCatch();
        tryCatch.getFileSize("a.java");	// 오류 발생: IOException을 처리하지 않음
    }
    catch (FileNotFoundException e) {
        e.printStackTrace();
    }
}
----

`catch` 문에서 `throws` 절에서 선언한 `Exception` 클래스의 부모 클래스 예외를 처리하도록 할 수 있습니다. 아래와 같이 `catch` 절에서 `Exception` 클래스 예외를 처리하도록 하여 모든 예외를 처리하도록 할 수 있습니다.


[source, java]
----
public int getFileSize(String fileName) throws IOException {
    return 1;
}

public static void main(String[] args) {
    try {
        TryCatch tryCatch = new TryCatch();
        tryCatch.getFileSize("a.java");	
    }
    catch (Exception e) {
        e.printStackTrace();
    }
}
----

`main` 메소드에서도 throws 절을 사용할 수 있습니다. main 메소드에서 throw 절을 사용하면 Java 가상 머신에서 예외를 처리합니다.

[source, java]
----
public static void main(String[] args) throws ClassNotFoundException {
    …
}
----

link:./26_throw.adoc[이전: throw statement (throw 문)] +
link:./28_finally.adoc[다음: finally statement (finally 문)]