= 예외 처리

[source, java]
----
public class Hello {
    public static void main(String[] args) {
        try {
            System.out.println(args[0]);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}
----

---

사용자는 응용 프로그램을 실행하는 과정에서 기대하기 어려운 응답을 입력하거나 존재하지 않는 파일을 호출할 수 있습니다. 오류 가능성은 무한합니다. 응용 프로그램은 사용자가 발생시킬 수 있는 예기치 않은 상황을 처리할 수 있어야 합니다. 아무리 많은 오류 검사를 코드에 추가하더라도 응용 프로그램에서는 언제나 오류가 발생할 수 있어야 합니다.

Java응용 프로그램에서 실행 오류(Runtime error)가 발생하면 예외(Exception)가 발생합니다. java에서는 위의 코드처럼 `try-catch` 구문을 사용하여 예외를 처리할 수 있습니다. 응용 프로그램의 `try` 절 내에 있는 구문이 실행 과정에서 예외를 발생하면 실행은 `catch` 절로 전송됩니다.

Exception 객체의 printStackTrace, getMessage등의 메소드를 사용하여 발생한 예외에 대한 정보를 알 수 있습니다. 위의 소스를 컴파일하고 파라미터 없이 실행하면 아래와 같이 런타임 오류가 처리됩니다.

----
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at Hello.main(Hello.java:4)
----

만약 예외를 처리하는 코드를 작성하지 않았다면 아래와 같이 런타임 오류가 발생됩니다.

----
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at Hello.main(Hello.java:3)
----

예외 처리에 대해서는 이후에 자세히 알아봅니다.

link:./14_javadoc.adoc[이전: javadoc] +
link:./16_demo2.adoc[다음: Demo - JavaDoc을 사용한 HTML 문서 생성]